### ISSUE TITLE
addImage not working in current SVN version

### ISSUE THREAD

**Issue by wurzerj** [davidgohel/ReporteRs#114] opened 2016-03-04 10:19 UTC
Hi David,

In the current SVN version (dated 2016/03/03) the addImage() function seems to be buggy. Maybe I  did not manage to compile the package from source properly, but it would be great if you could check. 

It crashes with the following error:
```
Fehler in .jcall(slide, "I", "add", jimg, .jfloat(offx_), .jfloat(offy_),  : 
  method add with signature (Lorg/lysis/reporters/img/Image;FFZ)I not found
```

Sample code:
```
require(ReporteRs)

doc <- pptx()

doc <- addSlide(doc, slide.layout="Title and Content")
doc <- addTitle(doc, "Title 1")
doc <- addParagraph(doc, "Paragraph 1")

doc <- addSlide(doc, slide.layout="Title and Content")
doc <- addTitle(doc, "Title 2")
doc <- addParagraph(doc, "Paragraph 2")

doc <- addSlide(doc, slide.layout="Title and Content")
doc <- addTitle(doc, "Title 3")
doc <- addImage(doc, filename="C:/Temp/temp.wmf")

writeDoc(doc, file="C:/Temp/test.pptx")
shell.exec("C:/Temp/test.pptx")
```

Session Info:
```
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=German_Austria.1252  LC_CTYPE=German_Austria.1252    LC_MONETARY=German_Austria.1252 LC_NUMERIC=C                    LC_TIME=German_Austria.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] RInnoUtils_0.05-45 plotrix_3.5-10     TTR_0.22-0         e1071_1.6-4        xts_0.9-7          zoo_1.7-11         RBlat_1.7.0-3      rcom_3.1-2         rscproxy_2.0-5    
[10] RInnoDB_2.4-7      RODBC_1.3-10      

loaded via a namespace (and not attached):
[1] class_7.3-11    grid_3.1.1      lattice_0.20-29 tools_3.1.1
```

Regards,

Jürgen

**Comment by davidgohel** [comment] 2016-03-04 10:32
Hi

Could you send me in PM the wmf file please? 

Also the sessionInfo() you've posted do not contain `ReporteRs`, could you rerun `sessionInfo()`?

Thanks

**Comment by wurzerj** [comment] 2016-03-04 12:19
Hi,

Sorry for the confusion. You can use any file you want, see modified sample code below.

Sample:
```
require(ReporteRs)

doc <- pptx()

doc <- addSlide(doc, slide.layout="Title and Content")
doc <- addTitle(doc, "Title 1")
doc <- addParagraph(doc, "Paragraph 1")

doc <- addSlide(doc, slide.layout="Title and Content")
doc <- addTitle(doc, "Title 2")
doc <- addParagraph(doc, "Paragraph 2")

win.metafile("C:/Temp/temp.wmf")
plot(rnorm(10), rnorm(10))
dev.off()

doc <- addSlide(doc, slide.layout="Title and Content")
doc <- addTitle(doc, "Title 3")
doc <- addImage(doc, filename="C:/Temp/temp.wmf")

writeDoc(doc, file="C:/Temp/test.pptx")
shell.exec("C:/Temp/test.pptx")
```

Copied sessionInfo() from the wrong R process bevore, sorry. Now ... ReporteRs_0.8.5 = built from Github source: 
```
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=German_Austria.1252  LC_CTYPE=German_Austria.1252    LC_MONETARY=German_Austria.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Austria.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] ReporteRs_0.8.5     ReporteRsjars_0.0.2 rcom_3.1-2          rscproxy_2.0-5      RInnoDB_2.4-7      
[6] RODBC_1.3-10       

loaded via a namespace (and not attached):
 [1] digest_0.6.4      gdtools_0.0.7     grid_3.1.1        htmltools_0.3     httpuv_1.3.3      knitr_1.12.3     
 [7] mime_0.3          png_0.1-7         R.methodsS3_1.7.1 R.oo_1.20.0       R.utils_2.2.0     R6_2.0.1         
[13] Rcpp_0.12.3       rJava_0.9-6       rvg_0.0.7         shiny_0.13.0      tools_3.1.1       xml2_0.1.1       
[19] xtable_1.7-4 
```

Regards,

Jürgen

**Comment by davidgohel** [comment] 2016-03-04 12:24
`win.metafile` is not available on R for mac. However, I've tried with a wmf file downloaded from the web and was not able to reproduce the issue.

**Comment by wurzerj** [comment] 2016-03-04 23:27
Maybe this is due to an improper built on my side; same addImage() code works without any problems with 0.8.5 on CRAN. Are you able to build a Windows package and send it via PM ,,, then I can test on a windows machine. If not I'd suggest to close my ticket.

Jürgen

**Comment by davidgohel** [comment] 2016-03-05 06:54
OK, 

This binaries can be downloaded during few hours:
http://win-builder.r-project.org/dzYIZcazEH03/ReporteRs_0.8.6.9000.zip

I am closing the ticket

David

**Closed by davidgohel** 2016-03-05 06:54 UTC
