### ISSUE TITLE
R crashes on printing a ggplot with cut rectangles in PowerPoint

### ISSUE THREAD

**Issue by luke-a** [davidgohel/ReporteRs#144] opened 2016-11-01 10:39 UTC
The following code crashes R: 

```
library(ReporteRs)
library(ggplot2)
p <- ggplot(mtcars, aes(wt, mpg)) + 
  geom_bin2d() +
  coord_cartesian(xlim = c(3,4), ylim = c(20, 25)) # some bin-rects are cut, now
doc <- pptx() 
doc <- addSlide(doc, slide.layout = slide.layouts(doc)[2]) # "Title and Vertical Text" 
doc <- addPlot(doc, print, x = p)
writeDoc(doc, tf <- tempfile(fileext = ".pptx"))
```
My session info:

```
sessionInfo()
# R version 3.3.1 (2016-06-21)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 7 x64 (build 7601) Service Pack 1
# 
# locale:
# [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
# [5] LC_TIME=German_Germany.1252    
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] ggplot2_2.1.0.9001  ReporteRs_0.8.6     ReporteRsjars_0.0.2
# 
# loaded via a namespace (and not attached):
#  [1] Rcpp_0.12.7         knitr_1.14          xml2_1.0.0          munsell_0.4.3       colorspace_1.2-7    xtable_1.8-2        R6_2.2.0           
#  [8] plyr_1.8.4          tools_3.3.1         grid_3.3.1          gtable_0.2.0        rvg_0.1.0           R.oo_1.20.0         png_0.1-7          
# [15] htmltools_0.3.5     assertthat_0.1      lazyeval_0.2.0.9000 digest_0.6.10       tibble_1.2          rJava_0.9-8         shiny_0.14.1       
# [22] R.utils_2.3.0       mime_0.5            gdtools_0.0.7       scales_0.4.0.9003   R.methodsS3_1.7.1   httpuv_1.3.3    
```

**Comment by davidgohel** [comment] 2016-11-04 16:58
Hi 

This is a duplicate of https://github.com/davidgohel/rvg/issues/7.

Could you update your packages? 

```
install.packages(c("gdtools", "rvg"))
```

I am preparing a new release for cran, you may need also:

 ```
devtools::install_github("davidgohel/ReporteRs")
```

Please tell me if the issue is not solved, I will reopen the issue.

**Closed by davidgohel** 2016-11-04 16:58 UTC

**Comment by luke-a** [comment] 2016-11-05 00:43
Thanks, updating all three of them did the trick. Great package(s) btw.
