### ISSUE TITLE
replace slide example not working

### ISSUE THREAD

**Issue by cdeterman** [davidgohel/ReporteRs#66] opened 2015-02-02 20:38 UTC
I just tried the example for replacing slides posted on the ReporeRs example pages (https://davidgohel.github.io/ReporteRs/powerpoint.html#UIDBdtHirxSx4).  I recreated the first example to generate a working pptx file and then tried the following code:

    mydoc = pptx(title='title', template = 'examples/pp_simple_example.pptx' )
    myplot = qplot(Sepal.Length, Petal.Length, data = iris, color = Species, size = Petal.Width, alpha = I(0.7))
    mydoc = addSlide( mydoc, slide.layout = 'Title and Content', bookmark=2)

At this point I get an error:
     
    Error in .jcall(doc$obj, paste0("L", class.pptx4r.SlidePart, ";"), "getAndReInitExistingSlide",  : 
     org.pptx4j.Pptx4jException: Can't add slide at index 1.  (There are 0 slides) 

Did I miss something?

**Comment by davidgohel** [comment] 2015-02-03 10:26
No, it was a bug. Thanks for letting me know.

It has just been fixed on github

David

**Comment by cdeterman** [comment] 2015-02-03 13:42
Thank you David but the replace example still doesn't seem to work appropriately.  If I run your example exactly from your examples directory.

    # demo slide replacement --------

    # define 2 FlexTables
    ft1 = vanilla.table( head( mtcars ), add.rownames = TRUE )
    ft2 = vanilla.table( head( iris ), add.rownames = TRUE )

    # create an doc to be used as template later
    mydoc = pptx( )
    mydoc = addSlide( mydoc, slide.layout = "Title and Content")
    mydoc = addTitle( mydoc, "a table") 
    mydoc = addFlexTable( mydoc, ft1 ) 
    mydoc = addSlide( mydoc, slide.layout = "Title and Content")
    mydoc = addTitle( mydoc, "some text")
    mydoc = addParagraph( mydoc, "text example" )
    writeDoc( mydoc, "template_example.pptx" )

    # use file pp_template_example.pptx as template
    # and replace slide 1 
    mydoc = pptx(template = "template_example.pptx" )
    mydoc = addSlide( mydoc, slide.layout = "Title and Content", bookmark = 1)
    mydoc = addTitle( mydoc, "a new table")
    mydoc = addFlexTable( mydoc, ft2 )
    writeDoc( mydoc, "slide_replacement.pptx" )

This results in a pptx with only one slide.  The first slide is different but the second slide does not exist.  Also, if I try to change the second slide with bookmark=2 it gives the same error as before.

**Comment by davidgohel** [comment] 2015-02-03 13:52
Can I get your sessionInfo() output please? (in some cases, this happen when library is not unattached while reinstalling the package)

I have ckecked with 
    devtools::install_github('davidgohel/ReporteRs')

Also installed from the binary, and the example is running as expected.

David

**Comment by cdeterman** [comment] 2015-02-03 13:56
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ReporteRs_0.7.5     ReporteRsjars_0.0.2 rJava_0.9-6        

loaded via a namespace (and not attached):
 [1] colorspace_1.2-4 digest_0.6.7     ggplot2_1.0.0    grid_3.1.2       gtable_0.1.2     MASS_7.3-35     
 [7] munsell_0.4.2    plyr_1.8.1       proto_0.3-10     Rcpp_0.11.3      reshape2_1.4.1   scales_0.2.4    
[13] stringr_0.6.2    tools_3.1.2

**Comment by davidgohel** [comment] 2015-02-03 14:16
OK, version is ok and we have the same environment.
I can't reproduce the issue as it worked on my centos, my windows, and my colleagues computer... 

I would try again to install the package but in a new fresh R session (without ReporteRs being loaded).

**Comment by cdeterman** [comment] 2015-02-03 14:52
Alright, not sure what my problem really was.  I ended up restarting my computer, creating a new R session, re-installing the package and now it works fine.  Thanks for the initial bug fix and confirming everything is working.

**Comment by davidgohel** [comment] 2015-02-03 14:54
you're welcome

david

**Closed by davidgohel** 2015-02-03 14:54 UTC
Labels: bug
